#!/bin/bash
#PBS -l walltime=03:30:00
#PBS -lselect=1:ncpus=12:mem=450gb
#PBS -J 1-2


#  #PBS -J 1-3

module load tools/prod

### ---- Load conda and activate python environment

module load miniforge/3
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate rojak

### ---- Copy source code and config file over

# THRESHOLDS_FILE="thresholds_2022-2025_calibration_2026-02-27.json"
# THRESHOLDS_FILE="distribution_params_2024___2026-02-27_09_37_35.json"
# THRESHOLDS_FILE="distribution_params_2025__2026-03-03_14_28_54.json"
#THRESHOLDS_FILE="distribution_params_2023-2025_2026-04-09.json" # THIS IS WHAT WAS USED IN DRAFT
THRESHOLDS_FILE="distribution_params_2023-2025__2026-05-18.json"
SOURCE_DIR="rojak-leaf"

cp -r "${PBS_O_WORKDIR}/${SOURCE_DIR}" "$TMPDIR" || exit
cp "${PBS_O_WORKDIR}/${THRESHOLDS_FILE}" "$TMPDIR/${SOURCE_DIR}/$THRESHOLDS_FILE" || exit

### ---- Move into folder where code will execute

cd "$TMPDIR/$SOURCE_DIR" || exit

# Delete existing venv (hopefully fixes path issue)
rm -r .venv

uv venv --python 3.12

# shellcheck source=/dev/null
source .venv/bin/activate

uv sync --all-groups --no-group dev --no-group docs --no-group test --all-extras

echo "folder: $EPHEMERAL/$FOLDER_NAME"

# python issr_and_turb.py "$EPHEMERAL/from-sancho-panza/era5/$FOLDER_NAME" "$IDENTIFIER"
# python issr-turb-same-col-counterfactual.py "$IDENTIFIER" \
#  "$EPHEMERAL/from-sancho-panza/era5/2025" \
#  "$EPHEMERAL/from-sancho-panza/era5/2023" \
#  "$THRESHOLDS_FILE" || exit
# python conditional-probabilities-array-job-flights.py "$IDENTIFIER" \
#  "$EPHEMERAL/from-sancho-panza/era5/all-years" \
#  "$THRESHOLDS_FILE" \
#  "$PBS_ARRAY_INDEX" \
#  "$EPHEMERAL/exported-diagnostics/distribution_2022-2025/all-together" || exit

# python conditional-probabilities-array-job-flights.py "$IDENTIFIER" \
#  "/rds/general/ephemeral/user/hlw16/ephemeral/issr" \
#  "$THRESHOLDS_FILE" \
#  "$PBS_ARRAY_INDEX" \
#  "$EPHEMERAL/exported-dignostics/distribution_2022-2025/all-together" || exit

# python relative-risk-velocity-mslp.py \
#  "$EPHEMERAL/from-sancho-panza/era5/all-years" \
#  "$EPHEMERAL/from-sancho-panza/era5/vertical-velocity/all-years" \
#  "$EPHEMERAL/from-sancho-panza/era5/surface-pressure/all-years" \
#  "/rds/general/user/hlw16/home/rojak_runs/results/$IDENTIFIER" \
#  "$THRESHOLDS_FILE" \
#  "$PBS_ARRAY_INDEX" || exit

#  "$EPHEMERAL/exported-diagnostics/distribution_2022-2025/all-together" \

# python relative-risk-velocity-mslp-stratified.py \
#  "$EPHEMERAL/exported-diagnostics/all-years/all-years" \
#  "$EPHEMERAL/issr" \
#  "$EPHEMERAL/from-sancho-panza/era5/vertical-velocity/all-years" \
#  "$EPHEMERAL/from-sancho-panza/era5/surface-pressure/all-years" \
#  "/rds/general/user/hlw16/home/rojak_runs/results/$IDENTIFIER" \
#  "$THRESHOLDS_FILE" \
#  "$PBS_ARRAY_INDEX" || exit

#python export-issr.py

python relative-risk-velocity-mslp-stratified-w-refactor.py \
 "$EPHEMERAL/exported-diagnostics/all-years/all-years" \
 "$EPHEMERAL/issr" \
 "$EPHEMERAL/from-sancho-panza/era5/vertical-velocity/all-years" \
 "/rds/general/user/hlw16/home/rojak_runs/results/$IDENTIFIER" \
 "$THRESHOLDS_FILE" \
 "$PBS_ARRAY_INDEX" || exit

# python relative-risk-velocity-mslp-stratified.py \
#  "$EPHEMERAL/exported-diagnostics/djf-2020-2025/djf-2020-2025" \
#  "$EPHEMERAL/issr" \
#  "$EPHEMERAL/from-sancho-panza/era5/vertical-velocity/all-years" \
#  "$EPHEMERAL/from-sancho-panza/era5/surface-pressure/all-years" \
#  "/rds/general/user/hlw16/home/rojak_runs/results/$IDENTIFIER" \
#  "$THRESHOLDS_FILE" \
#  "$PBS_ARRAY_INDEX" || exit
