#!/bin/bash
#PBS -l walltime=12:30:00
#PBS -lselect=1:ncpus=12:mem=920gb

module load tools/prod

### ---- Load conda and activate python environment

module load miniforge/3
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate rojak

### ---- Copy source code and config file over

cp -r "${PBS_O_WORKDIR}/${SOURCE_DIR}" "$TMPDIR"

config_dir=$(dirname "${CONFIG_FILE_PATH}")
mkdir -p "${TMPDIR}/${config_dir}"
cp "${PBS_O_WORKDIR}/$CONFIG_FILE_PATH" "${TMPDIR}/${CONFIG_FILE_PATH}" || exit

### ---- Copy config file over

output_dir=$(grep "output_dir:" "${PBS_O_WORKDIR}/${CONFIG_FILE_PATH}" | cut -d':' -f2 | tr -d ' ')
current_time=$(date +"%Y-%m-%d_%H-%M-%S")
echo "$output_dir"
mkdir -p "$output_dir"
config_basename=$(basename -s .yaml "$CONFIG_FILE_PATH")
cp "${PBS_O_WORKDIR}/$CONFIG_FILE_PATH" "${output_dir}/${current_time}_${config_basename}.yaml" || exit

### ---- Move into folder where code will execute

cd "$TMPDIR/$SOURCE_DIR" || exit

# Delete existing venv (hopefully fixes path issue)
rm -r .venv

uv venv --python 3.12

# shellcheck source=/dev/null
source .venv/bin/activate

uv sync --all-groups --no-group dev --no-group docs --no-group test --all-extras

cd "$TMPDIR" || exit

rojak lite turbulence "${LITE_COMMAND:-distribution-parameters}" \
    "${TMPDIR}/${CONFIG_FILE_PATH}" \
    "${LOAD_FROM:-precomputed_from_zarr}" || exit

echo $?
