#!/bin/bash
#PBS -l walltime=03:30:00
#PBS -lselect=1:ncpus=12:mem=450gb

module load tools/prod

### ---- Load conda and activate python environment

module load miniforge/3
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate rojak

### ---- Copy source code and config file over

THRESHOLDS_FILE="/path/to/distribution/params/json"
SOURCE_DIR="rojak-leaf"

cp -r "${PBS_O_WORKDIR}/${SOURCE_DIR}" "$TMPDIR" || exit
cp "${PBS_O_WORKDIR}/${THRESHOLDS_FILE}" "$TMPDIR/${SOURCE_DIR}/$THRESHOLDS_FILE" || exit

### ---- Move into folder where code will execute

cd "$TMPDIR/$SOURCE_DIR" || exit

# Delete existing venv (hopefully fixes path issue)
rm -r .venv

uv venv --python 3.12

# shellcheck source=/dev/null
source .venv/bin/activate

uv sync --all-groups --no-group dev --no-group docs --no-group test --all-extras

python export-issr.py
