spatial_domain:
  maximum_latitude: 70
  maximum_longitude: 180
  minimum_latitude: -70
  minimum_longitude: -180
name: distribution_2023-2025
output_dir: /path/to/output
chunks:
  pressure_level: 6
  latitude: 721
  longitude: 1440
data_dir: /path/to/exported/diagnostics/as/zarr
diagnostics:
  - richardson
  - negative_richardson
  - f2d
  - f3d
  - ubf
  - ti1
  - ti2
  - ncsu1
  - endlich
  - colson_panofsky
  - wind_speed
  - bunt_vaisala
  - vertical_wind_shear
  - deformation
  - directional_shear
  - temperature_gradient
  - horizontal_divergence
  - ngm1
  - ngm2
  - brown1
  - brown2
  - gradient_pv
  - nva
  - dutton
  - edr_lunnon
  - vorticity_squared
